model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 16384  # Keep same vocab size as current setup
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000  # Start discriminator after some training
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8  # Adjust based on your GPU memory
    num_workers: 8
    train:
      target: taming.data.celebahq_10k.CelebAHQ10KTrain
      params:
        size: 256
        crop_size: 256
    validation:
      target: taming.data.celebahq_10k.CelebAHQ10KValidation
      params:
        size: 256
        crop_size: 256



